### ISSUE TITLE
Handling of empty country groups

### ISSUE THREAD

**Issue by cl0ne** [ConstantineRudenko/euroDiffusion-cython#1]
According to requirements all valid cases should start with positive number
> The first line of each test case is the number of countries **(1 ≤ c ≤ 20)**
The **last case** in the input is followed by a **single zero**.

Probably we shouldn't add empty groups at all and just stop reading input
https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/de53a1a6c6f6c142a0143d7f3d9ca89a28db5d5a/lab.pyx#L244-L246

Also I think its redundant to create `Simulator` for empty groups:
https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/de53a1a6c6f6c142a0143d7f3d9ca89a28db5d5a/lab.pyx#L274-L277

**Comment by ConstantineRudenko** [comment]
now we stop reading when 0 sized group is encountered without creating `Simulator`:

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/405046d3986492a2a2c960660a46148277c43560/lab.pyx#L293-L299

**Comment by cl0ne** [comment]
But we're still add it and other following groups to the list
https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/405046d3986492a2a2c960660a46148277c43560/lab.pyx#L255
