### ISSUE TITLE
City index

### ISSUE THREAD

**Issue by IanaKhitsko** [ConstantineRudenko/euroDiffusion-cython#10]
https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/9eed3607144d9f72a19069795f9a4e52308972d8/lab.pyx#L151

cur_city_index will be always x*max_y+y ? if so, do we need that variable?

**Comment by ConstantineRudenko** [comment]
i believe simple increment is easier to read and understand than trying to guess what the formula is supposed to mean
