### ISSUE TITLE
Indexing

### ISSUE THREAD

**Issue by IanaKhitsko** [ConstantineRudenko/euroDiffusion-cython#11]
Can x_index, y_index be -1 ? 

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/9eed3607144d9f72a19069795f9a4e52308972d8/lab.pyx#L180

**Comment by ConstantineRudenko** [comment]
-1 is a valid index and points at the last element

this will not cause the first and last element to be treated as neighbors because city_matrix has padding to prevent it

padding allows to skip checks for index being out of bounds
