### ISSUE TITLE
Exception catch abuse?

### ISSUE THREAD

**Issue by cl0ne** [ConstantineRudenko/euroDiffusion-cython#2]
I see catching the most specific exceptions ("catch what you can handle") as a better approach than catching all exceptions at once:
https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/de53a1a6c6f6c142a0143d7f3d9ca89a28db5d5a/lab.pyx#L236-L242
https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/de53a1a6c6f6c142a0143d7f3d9ca89a28db5d5a/lab.pyx#L255-L259
For example, it'll catch `KeyboardInterrupt` too (yeah, I know, probability is low, but the message will be wrong).

**Comment by ConstantineRudenko** [comment]
fixed:

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/405046d3986492a2a2c960660a46148277c43560/lab.pyx#L23-L33

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/9d347b55f7efead8116294116d494d7eac7dfaab/lab.pyx#L247-L253

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/9d347b55f7efead8116294116d494d7eac7dfaab/lab.pyx#L266-L270
