### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by cl0ne** [ConstantineRudenko/euroDiffusion-cython#3]
I suppose this twoo loops can be merged
https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/de53a1a6c6f6c142a0143d7f3d9ca89a28db5d5a/lab.pyx#L88-L97
The only reason I see why it can separated &ndash; to skip overlapping countries, but this can be detected in the first loop as well.

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/de53a1a6c6f6c142a0143d7f3d9ca89a28db5d5a/lab.pyx#L80-L85
why not use here list comprehensions and other syntactic sugar?
```python
 city_matrix = [[-1] * max_y for x in range(max_x)]
```

**Comment by ConstantineRudenko** [comment]
loops merged:

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/9d347b55f7efead8116294116d494d7eac7dfaab/lab.pyx#L97-L106

regarding list comprehensions - i think it would sacrifice readability without much benefit

**Comment by cl0ne** [comment]
Also I think it'd be better to reduce size of this enormous loop to something smaller by extracting some code into methods, right?
https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/9d347b55f7efead8116294116d494d7eac7dfaab/lab.pyx#L174-L228

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/9d347b55f7efead8116294116d494d7eac7dfaab/lab.pyx#L214-L222
We can lower nesting by checking `else` condition first with `continue`

**Comment by cl0ne** [comment]
https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/9d347b55f7efead8116294116d494d7eac7dfaab/lab.pyx#L252
Here and in other similar places, `str.format` actually is not really needed, [print function](https://docs.python.org/3.5/library/functions.html#print) accepts a list of positional arguments and will join them together with value from `sep` keyword argument (which is by default is single space)

**Comment by ConstantineRudenko** [comment]
checking for finished countries  extracted into separate method:

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/8bb3b0f1fdb0a139ba9d4fde43301ff9fa2c4dd6/lab.pyx#L241-L247

nesting reduced:

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/8bb3b0f1fdb0a139ba9d4fde43301ff9fa2c4dd6/lab.pyx#L263-L272

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/8bb3b0f1fdb0a139ba9d4fde43301ff9fa2c4dd6/lab.pyx#L148-L160

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/8bb3b0f1fdb0a139ba9d4fde43301ff9fa2c4dd6/lab.pyx#L168-L183

use of `str.format()` removed when unnecessary

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/8bb3b0f1fdb0a139ba9d4fde43301ff9fa2c4dd6/lab.pyx#L313-L315

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/8bb3b0f1fdb0a139ba9d4fde43301ff9fa2c4dd6/lab.pyx#L327

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/8bb3b0f1fdb0a139ba9d4fde43301ff9fa2c4dd6/lab.pyx#L335

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/8bb3b0f1fdb0a139ba9d4fde43301ff9fa2c4dd6/lab.pyx#L362
