### ISSUE TITLE
Constants

### ISSUE THREAD

**Issue by IanaKhitsko** [ConstantineRudenko/euroDiffusion-cython#6]
Consider moving all 'magic numbers' to const variables 

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/9eed3607144d9f72a19069795f9a4e52308972d8/lab.pyx#L37

**Comment by ConstantineRudenko** [comment]
done

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/daccb24cd79768291d89ed6e30018931e0971f9c/lab.pyx#L8-L14
