### ISSUE TITLE
Type for iteration class member

### ISSUE THREAD

**Issue by IanaKhitsko** [ConstantineRudenko/euroDiffusion-cython#7]
Why do you need such type for iteration? 

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/9eed3607144d9f72a19069795f9a4e52308972d8/lab.pyx#L87

**Comment by ConstantineRudenko** [comment]
I don't
fixed
https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/daccb24cd79768291d89ed6e30018931e0971f9c/lab.pyx#L95
