### ISSUE TITLE
struct City -> class City

### ISSUE THREAD

**Issue by IanaKhitsko** [ConstantineRudenko/euroDiffusion-cython#8]
https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/9eed3607144d9f72a19069795f9a4e52308972d8/lab.pyx#L63

Can City be a class with contraction and desctuction? Thus you won't need Destroy_city function and other things will look simplier

**Comment by ConstantineRudenko** [comment]
C++ classes are not available in Cython.
They can only be used by creating wrappers which in this case defeats the purpose.

The reason _City is a C struct and not a python class is the speed boost compared to python classes.
