### ISSUE TITLE
Some magic is making here 

### ISSUE THREAD

**Issue by IanaKhitsko** [ConstantineRudenko/euroDiffusion-cython#9]
What is it about? 

https://github.com/ConstantineRudenko/euroDiffusion-cython/blob/9eed3607144d9f72a19069795f9a4e52308972d8/lab.pyx#L116-L117

**Comment by ConstantineRudenko** [comment]
the array leaves additional elements before the first coordinate and after the last coordinate

this is done so that when looking for neighbors i do not have to worry about going out of bounds

**Comment by IanaKhitsko** [comment]
ok, but you should describe it somehow. use constants or comments
